name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.11.1
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.1
        cache: 'npm'
    - run: make install
    - run: make test
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v6.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
      with:
        coverageCommand: npm test -- --coverage
